### ISSUE TITLE
Cannot use  pipenv run python src/cli.py

### ISSUE THREAD

**Issue by JackingChen** [TW-NCHC/TWCC-CLI#2]
I have followed the instructions under TW-NCHC/TWCC-CLI/README.md and running  
`pipenv run python src/test/gpu_cntr.py` works well
However, I'm having trouble with the functions in src/cli.py 
![image](https://user-images.githubusercontent.com/11462455/59652242-75a46580-91bf-11e9-81d4-9c99b3e76ede.png)
(above is the snapshot of the error)
it says KeyError: 'sys'

This is the same when entering command:
`pipenv run python src/cli.py snapshots -l`
![image](https://user-images.githubusercontent.com/11462455/59652292-b7351080-91bf-11e9-91bb-f45bc0f6fd31.png)

**Comment by NCHC-InfraServ** [comment]
this issue will not occur again after you update to latest code, close for now
