### ISSUE TITLE
Can not run `pipenv run python /src/test/gpu_cntr.py`

### ISSUE THREAD

**Issue by itsjeffreyy** [TW-NCHC/TWCC-CLI#6]
I follow the steps on the [TWCC CLI](https://www.twcc.ai/doc?page=deploy_env_cli) to deploy operating environment on my own computer (OS Ubuntu 18.04).
I already installed `python2.7` and `python2.7-dev`, so I execute the command as follow:
```
sudo pip install pipenv
git clone https://github.com/TW-NCHC/TWCC-CLI
cd TWCC-CLI/
pipenv install
pipenv run python src/test/gpu_cntr.py
```

I got the message:
```
>>>>>>>>>> Welcome to  TWCC.ai  <<<<<<<<<<
Traceback (most recent call last):
  File "src/test/gpu_cntr.py", line 15, in <module>
    from twcc.util import pp, table_layout, SpinCursor, isNone
  File "/home/jeffreyy/program/TWCC-CLI/src/twcc/__init__.py", line 4, in <module>
    from twcc.session import session_start
  File "/home/jeffreyy/program/TWCC-CLI/src/twcc/session.py", line 6, in <module>
    from twcc.util import *
  File "/home/jeffreyy/program/TWCC-CLI/src/twcc/util.py", line 1, in <module>
    import threading
ImportError: No module named threading
```

**Comment by JeanHsuBD** [comment]
Hi there, 

From your error message we found that there're some error in your python library. The solution for this `rm -rf ~/.local` to clean your existing python lib. Then do how to again.

Also, the version v0.1 will not be used in the future. Please try v0.5 for better user experience! Tks!
