### ISSUE TITLE
Running `python src/test/s3.py list-buckets` gives me an error.

### ISSUE THREAD

**Issue by Nash2325138** [TW-NCHC/TWCC-CLI#7]
Hi TWCC-CLI team,
Our project is deducted by 「雲端資源」 service:
![82664379-2e8ee200-9c64-11ea-9d86-8e386d7c0893](https://user-images.githubusercontent.com/17662095/82664827-297e6280-9c65-11ea-89b1-99c0c31afbbd.png)

But on the web interface, I can't find anything related to that deduction: 
![image](https://user-images.githubusercontent.com/17662095/82664605-a2c98580-9c64-11ea-9606-86fb4cbae833.png)

So, now I'm trying to use `TWCC-CLI` to find out more information, but when I ran the command `python src/test/s3.py list-buckets`, I ran into the following bug:
![image](https://user-images.githubusercontent.com/17662095/82664236-d7890d00-9c63-11ea-8362-86b2b080f334.png)

Is it normal?
Or should I wait for v0.5 before further investing that deduction problem?

**Comment by NCHC-InfraServ** [comment]
hi, there, 

1. TWCC-CLI v0.1 is no longer maintain. please try v0.5 series
2. and try to install `pip install TWCC-CLI==0.5.12rc1` and sync all objects by using `twccli cp cos -bkt $BUCKET_NAME -dir $LOCAL_DIR -sync from-cos` 
3. you also can use [s3cmd](https://www.google.com/search?client=safari&rls=en&q=s3cmd&ie=UTF-8&oe=UTF-8) to access TWCC COS service.


TWCC COS is compatible for all [object storage services](https://en.wikipedia.org/wiki/Object_storage), thanks for using TWCC.

**Comment by JeanHsuBD** [comment]
Hi @Nash2325138 ,

It's a message from TWCC-CLI team.
Is everything goes right?

The version v0.5.12 will be released this friday. And this issue will be closed in next week Jun. 6th.
Let us know, if you have any suggestion or question! Thank you!!

**Comment by Nash2325138** [comment]
I was working on some important deadlines last week and haven't tested it yet.
I will use the v0.5.12 tomorrow and will let you know if I encounter any problem

**Comment by Nash2325138** [comment]
Hi,
I installed the new version twcccli via pip (inside a container) following this [doc](https://man.twcc.ai/@twccdocs/twcc-cli-v05#TWCC-CLI-%CE%B1). The installation is successful and the following texts showed up:

<img src="https://user-images.githubusercontent.com/17662095/83964711-55464d00-a8e1-11ea-9ecc-17f4a102dbfe.png" width="250" height="150">

, but when I typed `twccli config init`, this error popped out
![image](https://user-images.githubusercontent.com/17662095/83964892-62b00700-a8e2-11ea-8e47-0438bc6985a3.png)

The same error happens on other commands like `twccli ls ccs` and `twccli ls cos`

It persists after I
```
export LANG=C.UTF-8
export LC_ALL=C.UTF-8
export PYTHONIOENCODING=UTF-8
```

What should I do to get rid of this error?

**Comment by JeanHsuBD** [comment]
Hi @Nash2325138 ,

Thank you for using the latest version v0.5.12!
We've found that there are python package problem in your error message.
Please tried:

`rm -rf ~/.twcc_data`
`rm -rf ~/.twcc_data`
`pip install TWCC-CLI`

to re-install the CLI tool.

Let us know, if you have any suggestion or question!

**Comment by JeanHsuBD** [comment]
If everything goes well,  #7 will be closed on June 15th. 

Thanks!

**Comment by Nash2325138** [comment]
I just removed `~/.twcc_data` and re-install TWCC-CLI via pip. The previous error is solved, but another popped out:

![14264760-d2e1-4b91-92c8-503247b8d49d](https://user-images.githubusercontent.com/17662095/84145331-44860a80-aa8c-11ea-98b7-8e1028127d4c.png)

Is there any possible mistake I've made?

**Comment by JeanHsuBD** [comment]
Hi @Nash2325138 

Sorry about the command mistake I wrote in [this block](https://github.com/TW-NCHC/TWCC-CLI/issues/7#issuecomment-640438891). Please tried:

```bash=
rm -rf ~/.twcc_data
rm -rf ~/.local  
pip install TWCC-CLI
```
to solve the package error.

And for the [error message](https://github.com/TW-NCHC/TWCC-CLI/issues/7#issuecomment-641245160) above, please check out our[ User Manual (⚠️ draft!! ⚠️ ) in #1-3](https://man.twcc.ai/@twccdocs/twcc-cli-v05#1-3-%E9%80%B2%E5%85%A5-TWCC_CLI-%E7%92%B0%E5%A2%83%E4%B8%A6%E9%96%8B%E5%A7%8B%E4%BD%BF%E7%94%A8%E6%9C%8D%E5%8B%99), to see if your **project code** been typed correctly.

Let us know, if we solved your issue and problems above!
Also, if there is any progress, please let us know promptly!! Thank you!

**Comment by Nash2325138** [comment]
Hi, I solved [the problem](https://github.com/TW-NCHC/TWCC-CLI/issues/7#issuecomment-641245160) after using the project code shown on the page "TWCC API 金鑰管理" instead of the one shown in "iService 計畫資訊".

I'll let you know if I have any other problem

**Comment by Nash2325138** [comment]
Hi, I've successfully executed `twccli ls cos`, and no `Cloud Object Storage`'s object shows up.

We suspect the mysterious deductions mentioned in the first post are caused by the not-suspended containers when TWGC services were closed. We will ask about this by another email.

Anyway, thanks for the troubleshooting to help me use `TWCC-CLI`! (You can close this issue now)

**Comment by JeanHsuBD** [comment]
Hi @Nash2325138 

Thank you very much for letting us know your problem using `TWCC-CLI`! 
Hope you get the solution for the deduction problem, after connect to our [Support](mailto:isupport@narlabs.org.tw) team!

All the questions, concerns, or suggestions are very welcome! :)
