### ISSUE TITLE
UnboundLocalError: local variable 'FileNotFoundError' referenced before assignment

### ISSUE THREAD

**Issue by theblackcat102** [TW-NCHC/TWCC-CLI#8]
**Describe the bug**

Executing unsupported command twccli fdsafd

**To Reproduce**

1. Install twcc-cli 0.5 version 
2. execute `twccli fdsafd`
3. See error

**Expected behavior**

A message like this should be returned:

```
Usage: twccli.py [OPTIONS] COMMAND [ARGS]...
Try "twccli.py --help" for help.

Error: No such command "fdsafd".
```

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS Catalina 10.15.5]
 - Python 3.6, 3.8

**Comment by theblackcat102** [comment]
Can we simply just handle IOError first followed by FileNotFoundError

```
class TWCCLI(click.MultiCommand):
    ...
    def get_command(self, ctx, name):
        ...
        try:
            with open(fn, 'rb') as f:
                txt = f.read()
        except IOError:
            click.echo('')
            return
        except FileNotFoundError:
            click.echo('')
            return

```

Executing  `twccli fdsafd` should return the following results

```
Usage: twccli.py [OPTIONS] COMMAND [ARGS]...
Try "twccli.py --help" for help.

Error: No such command "fdsafd".
```

**Comment by JeanHsuBD** [comment]
Hi there,

> No such command "fdsafd".
Please folloewed our [user manual](https://man.twcc.ai/@twccdocs/twcc-cli-v05) while using TWCC-CLI.
This tool was an unix-like handy command design. It can be use by `ls`, `mk`, `rm`... or more, but no `fdsafd`.

> Can we simply just handle IOError first followed by FileNotFoundError
Thank you for your suggestion, we will modify this issue in next release version!

**Comment by theblackcat102** [comment]
I understand the command isn't inside the listed command. But when cli is handling exception, the current method is wrong ( you can't just assign FileNotFoundError as IOError )

**Comment by JeanHsuBD** [comment]
Thank you again for this suggestion. 
The error message and your recommend has already been noted.
Our team will discuss and modify this issue in next release version.

If you have some more advice, please let us know! 
Or #8 will be closed on Nov. 6th.

Thank you very much!

**Comment by NCHC-InfraServ** [comment]
according to https://stackoverflow.com/a/21368457, py2 don't have `FileNotFoundError`. 

for overall compatibility, we choose to overwrite this error. 

~wontfix
